- name: PLAY-01
  hosts: web
  tasks:
  - name: printing the default message of PLAY-01 TASK-01
    ansible.builtin.debug:
      msg: "This is from PLAY-01 and TASK-01"
  
  - name: printing the default message of PLAY-02 TASK-01
    ansible.builtin.debug:
      msg: "This is from PLAY-02 and TASK-01"