- name: Connecting to the Server
  hosts: web
  become: yes # taking sudo or root access
  tasks:
  - name: Installing the nginx server
    ansible.builtin.package: # hetrogenous module that can work for all
      name: nginx
      state: present

  - name: starting the services
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes