- name: Connecting to Server 
  hosts: web
  vars_files:
   - vars.yaml
  tasks:
   - name: Variables allign from the outside other file  
     ansible.builtin.debug:
       msg: "Hi All, I'm learning {{COURSE}} course, duration is {{DURATION}} and the trainer is {{TRAINER}} "