- name: different types of datatypes
  hosts: local
  connection: local
  vars:
   course: "Devops with AWS" #string
   duration: 120hrs #number
   topics: #Lists (-)
     - Linux
     - Shell
     - Ansible
   live: true #boolean
   tools: #map/Dictonory
    ci: jenkins
    CM: ansible # string
    cloud: AWS
    AWS:
     - IAM
     - S3
     - EC2
  tasks: 
    - name: print the course information
      ansible.builtin.debug:
        msg: "Hi, I'm learning {{ course }}, with duration: {{ duration }}, topics are: {{ topics }}, and live: {{ live }}, tools are: {{ tools }}"
