- name: Creating inventory using the YAML 
  myhosts:
    hosts:
#     my_hosts_01:
#        ansible_host: <IP>
      my_hosts_02:
         ansible_host: 172.31.29.107
         http_port: 443
  tasks:
    - name: ping the ansilbe YAML hosts
      ansible.builtin.ping:


# creating multiple hosts:
# - name: creating multiple
#   leafs:
#     hosts:
#       leaf01:
#           ansible_host: 192.0.2.100
#       leaf02:
#           ansible_host: 192.0.2.110

#     spines:
#       hosts:
#         spine01:
#           ansible_host: 192.0.2.120
#         spine02:
#           ansible_host: 192.0.2.130

#     network:
#       children:
#         leafs:
#         spines:

#     webservers:
#       hosts:
#         webserver01:
#           ansible_host: 192.0.2.140
#         webserver02:
#           ansible_host: 192.0.2.150

#     datacenter:
#       children:
#         network:
#         webservers: